"""add users table

Revision ID: 13300239a8eb
Revises: 32ecd180d056
Create Date: 2026-08-11 14:16:34.321762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13300239a8eb'
down_revision: Union[str, Sequence[str], None] = '32ecd180d056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'daily_user_summaries',
        sa.Column(
            'words_found',
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    op.execute("UPDATE daily_user_summaries SET words_found = '{}'::text[] WHERE words_found IS NULL")
    op.alter_column('daily_user_summaries', 'words_found', server_default=None)
    op.create_foreign_key(
        'fk_daily_user_summaries_user_id_users',
        'daily_user_summaries',
        'users',
        ['user_id'],
        ['id'],
    )
    op.alter_column('dictionary', 'word',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(
        'fk_point_transactions_user_id_users',
        'point_transactions',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_point_transactions_user_id_users', 'point_transactions', type_='foreignkey')
    op.alter_column('dictionary', 'word',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('fk_daily_user_summaries_user_id_users', 'daily_user_summaries', type_='foreignkey')
    op.drop_column('daily_user_summaries', 'words_found')
    op.drop_table('users')
    # ### end Alembic commands ###
