"""add daily plates table

Revision ID: 484988ce56c7
Revises: e6cd470cbd5a
Create Date: 2026-09-15 16:24:05.328805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484988ce56c7'
down_revision: Union[str, Sequence[str], None] = 'e6cd470cbd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sequence', sa.String(length=3), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('goal_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_daily_plates_date'), 'daily_plates', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plates_date'), table_name='daily_plates')
    op.drop_table('daily_plates')
    # ### end Alembic commands ###
