"""add elapsed_seconds and tier_times to daily_user_summaries

Revision ID: a025c833af36
Revises: 869052d74a26
Create Date: 2026-09-08 14:34:59.926084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a025c833af36'
down_revision: Union[str, Sequence[str], None] = '869052d74a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'daily_user_summaries', 
        sa.Column('elapsed_seconds', sa.Integer(), server_default='0', nullable=False)
    )
    op.add_column(
        'daily_user_summaries', 
        sa.Column('tier_times', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False)
    )
    op.drop_index(op.f('ix_daily_summaries_date_points'), table_name='daily_user_summaries')
    op.create_index('ix_daily_summaries_date_points', 'daily_user_summaries', ['date', sa.literal_column('points_earned DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_summaries_date_points', table_name='daily_user_summaries')
    op.create_index(op.f('ix_daily_summaries_date_points'), 'daily_user_summaries', ['date', 'points_earned'], unique=False)
    op.drop_column('daily_user_summaries', 'tier_times')
    op.drop_column('daily_user_summaries', 'elapsed_seconds')
    # ### end Alembic commands ###
