"""add archive fields to daily_user_summaries

Revision ID: e6cd470cbd5a
Revises: a025c833af36
Create Date: 2026-09-15 14:05:44.354219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6cd470cbd5a'
down_revision: Union[str, Sequence[str], None] = 'a025c833af36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_user_summaries', sa.Column('archive_words_found', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('daily_user_summaries', sa.Column('archive_points_earned', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_user_summaries', 'archive_points_earned')
    op.drop_column('daily_user_summaries', 'archive_words_found')
    # ### end Alembic commands ###
